### ISSUE TITLE
DB Query error 

### ISSUE THREAD

**Issue by ghost** [Mamiglia/Reddit-Wallpaper#11] opened 2021-09-23 19:20 UTC
The new installer/window looks great. Problem is I can't expand it... to read the whole log. 

The error I am seeing is: 

INFO: No unused wallpaper is found, setting the ... 
WARNING: DB Query error in select()

The app works, but sometimes, it freezes on a wallpaper and I can't seem to change any settings.

**Comment by Mamiglia** [comment] 2021-09-23 19:42
Yeah, I removed the maximize button because I thought nobody used it. Isn't there a horizontal slider?

Anyway try erasing the database

**Comment by ghost** [comment] 2021-09-24 12:22
Yes, I do see the scroll bars... now! They work... but, being able to make the window larger would be better... just a preference, especially to read log!

I erased the wallpaper database, still had the problem. 

Then, I uninstalled the program and re-installed it. (note to self: lost all the downloaded wallpapers... will backup elsewhere next time). Now, I don't have any dB query error! Let's see if I run into this issue again! Thanks!

**Comment by Myraaleth** [comment] 2021-12-06 23:33
Hi! At a glance this looks like it could be the same problem I was talking to you about earlier.

**Comment by Mamiglia** [comment] 2021-12-07 13:16
No, this one is caused by DB issues. In particular I believe that the cause is that I store the Wallpaper objects inside the DB. When I updated the App I also changed the Wallpaper object structure. This caused an issue because the old wallpaper objects weren't recognized as Wallpaper objects, since they had changed their properties and functions

**Comment by Mamiglia** [comment] 2022-07-19 17:44
Hopefully the current release fixes this issue. Until then I'm gonna close this Issue

**Closed as completed by Mamiglia** 2022-07-19 17:44 UTC
Labels: bug
